//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTrack.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FailureAnalysisEntities : DbContext
    {
        public FailureAnalysisEntities()
            : base("name=FailureAnalysisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FabSites> FabSites { get; set; }
        public virtual DbSet<FAR_DeviceDetails> FAR_DeviceDetails { get; set; }
        public virtual DbSet<FAR_Master> FAR_Master { get; set; }
        public virtual DbSet<FAR_Mechanism> FAR_Mechanism { get; set; }
        public virtual DbSet<LOG_FARAnalystReassign> LOG_FARAnalystReassign { get; set; }
        public virtual DbSet<LOG_FARFinalTarget> LOG_FARFinalTarget { get; set; }
        public virtual DbSet<LOG_FARHistory> LOG_FARHistory { get; set; }
        public virtual DbSet<LOG_FARInitialTarget> LOG_FARInitialTarget { get; set; }
        public virtual DbSet<LOG_FARPriority> LOG_FARPriority { get; set; }
        public virtual DbSet<LOG_FARUpload> LOG_FARUpload { get; set; }
        public virtual DbSet<LOG_ProcessHistory> LOG_ProcessHistory { get; set; }
        public virtual DbSet<MST_AssemblySites> MST_AssemblySites { get; set; }
        public virtual DbSet<MST_BU> MST_BU { get; set; }
        public virtual DbSet<MST_Customer> MST_Customer { get; set; }
        public virtual DbSet<MST_Department> MST_Department { get; set; }
        public virtual DbSet<MST_FailureOrigin> MST_FailureOrigin { get; set; }
        public virtual DbSet<MST_FailureType> MST_FailureType { get; set; }
        public virtual DbSet<MST_FARReport> MST_FARReport { get; set; }
        public virtual DbSet<MST_LabSite> MST_LabSite { get; set; }
        public virtual DbSet<MST_Origin> MST_Origin { get; set; }
        public virtual DbSet<MST_PackageTypes> MST_PackageTypes { get; set; }
        public virtual DbSet<MST_Priority> MST_Priority { get; set; }
        public virtual DbSet<MST_ProcessProduct> MST_ProcessProduct { get; set; }
        public virtual DbSet<MST_ProcessResult> MST_ProcessResult { get; set; }
        public virtual DbSet<MST_ProcessTypes> MST_ProcessTypes { get; set; }
        public virtual DbSet<MST_Rating> MST_Rating { get; set; }
        public virtual DbSet<MST_Reason> MST_Reason { get; set; }
        public virtual DbSet<MST_ReasonChangingFINTarget> MST_ReasonChangingFINTarget { get; set; }
        public virtual DbSet<MST_ReasonChangingINITarget> MST_ReasonChangingINITarget { get; set; }
        public virtual DbSet<MST_ReasonChangingPriority> MST_ReasonChangingPriority { get; set; }
        public virtual DbSet<MST_ReasonFARClose> MST_ReasonFARClose { get; set; }
        public virtual DbSet<MST_ReasonFAROnHold> MST_ReasonFAROnHold { get; set; }
        public virtual DbSet<MST_ReasonFINReport> MST_ReasonFINReport { get; set; }
        public virtual DbSet<MST_ReasonINIReport> MST_ReasonINIReport { get; set; }
        public virtual DbSet<MST_ReportTypes> MST_ReportTypes { get; set; }
        public virtual DbSet<MST_Services> MST_Services { get; set; }
        public virtual DbSet<MST_Sites> MST_Sites { get; set; }
        public virtual DbSet<MST_Status> MST_Status { get; set; }
        public virtual DbSet<MST_Technology> MST_Technology { get; set; }
        public virtual DbSet<SYS_Roles> SYS_Roles { get; set; }
        public virtual DbSet<SYS_Users> SYS_Users { get; set; }
        public virtual DbSet<FAR_ProcessHistory> FAR_ProcessHistory { get; set; }
        public virtual DbSet<MST_Product> MST_Product { get; set; }
    }
}
