//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTrack.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAR_ProcessHistory
    {
        public FAR_ProcessHistory()
        {
            this.LOG_ProcessHistory = new HashSet<LOG_ProcessHistory>();
        }
    
        public int Id { get; set; }
        public int DeviceId { get; set; }
        public int ProcessTypeId { get; set; }
        public Nullable<int> ProcessResultId { get; set; }
        public bool IsIncluded { get; set; }
        public string Description { get; set; }
        public int SeqNum { get; set; }
        public Nullable<int> Iteration { get; set; }
        public string Analystor { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public string Comment { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> PlannedIN { get; set; }
        public Nullable<System.DateTime> PlannedOUT { get; set; }
    
        public virtual FAR_DeviceDetails FAR_DeviceDetails { get; set; }
        public virtual MST_ProcessResult MST_ProcessResult { get; set; }
        public virtual MST_ProcessTypes MST_ProcessTypes { get; set; }
        public virtual ICollection<LOG_ProcessHistory> LOG_ProcessHistory { get; set; }
    }
}
