//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTrack.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAR_DeviceDetails
    {
        public FAR_DeviceDetails()
        {
            this.FAR_ProcessHistory = new HashSet<FAR_ProcessHistory>();
        }
    
        public int Id { get; set; }
        public int MasterId { get; set; }
        public string LotNo { get; set; }
        public string MfgPartNo { get; set; }
        public int TechnologyId { get; set; }
        public int PackageTypeId { get; set; }
        public int AssembliesSiteId { get; set; }
        public int FabSiteId { get; set; }
        public int ServiceId { get; set; }
        public string DateCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public bool Stage { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> MechanismId { get; set; }
        public string FailureDetail { get; set; }
        public string WaferNo { get; set; }
        public string SerialNo { get; set; }
    
        public virtual FabSites FabSites { get; set; }
        public virtual FAR_Master FAR_Master { get; set; }
        public virtual MST_AssemblySites MST_AssemblySites { get; set; }
        public virtual MST_PackageTypes MST_PackageTypes { get; set; }
        public virtual MST_Services MST_Services { get; set; }
        public virtual FAR_Mechanism FAR_Mechanism { get; set; }
        public virtual MST_Technology MST_Technology { get; set; }
        public virtual ICollection<FAR_ProcessHistory> FAR_ProcessHistory { get; set; }
    }
}
