//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTrack.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterimAnalysis
    {
        public long Id { get; set; }
        public string FAR_Number { get; set; }
        public string report_type { get; set; }
        public string report_name { get; set; }
        public string report_location { get; set; }
        public Nullable<int> delay_reason { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public string upload_by { get; set; }
    }
}
