//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTrack.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_FARUpload
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public string FAType { get; set; }
        public string FileName { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public string UploadedBy { get; set; }
    }
}
