//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTrack.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_ProcessTypes
    {
        public MST_ProcessTypes()
        {
            this.MST_ProcessProduct = new HashSet<MST_ProcessProduct>();
            this.MST_ProcessResult = new HashSet<MST_ProcessResult>();
            this.FAR_ProcessHistory = new HashSet<FAR_ProcessHistory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<int> SeqNumber { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<MST_ProcessProduct> MST_ProcessProduct { get; set; }
        public virtual ICollection<MST_ProcessResult> MST_ProcessResult { get; set; }
        public virtual ICollection<FAR_ProcessHistory> FAR_ProcessHistory { get; set; }
    }
}
