//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTrack.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Reason
    {
        public MST_Reason()
        {
            this.LOG_FARHistory = new HashSet<LOG_FARHistory>();
            this.LOG_FARPriority = new HashSet<LOG_FARPriority>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<LOG_FARHistory> LOG_FARHistory { get; set; }
        public virtual ICollection<LOG_FARPriority> LOG_FARPriority { get; set; }
    }
}
