//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTrack.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Product
    {
        public MST_Product()
        {
            this.MST_ProcessProduct = new HashSet<MST_ProcessProduct>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string MainPerson { get; set; }
        public string SecondaryPerson { get; set; }
        public string TertiaryPerson { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool IsDeleted { get; set; }
        public int LabSiteId { get; set; }
    
        public virtual ICollection<MST_ProcessProduct> MST_ProcessProduct { get; set; }
        public virtual MST_LabSite MST_LabSite { get; set; }
    }
}
