//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTrack.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Users
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string Salt { get; set; }
        public System.DateTime RegistedDate { get; set; }
        public bool IsLocked { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool IsDeleted { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Phone { get; set; }
        public int DepartmentId { get; set; }
        public int SiteId { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public int RoleId { get; set; }
        public string RecoverPass { get; set; }
        public bool IsComfiredEmail { get; set; }
        public string Guid { get; set; }
    
        public virtual MST_Department MST_Department { get; set; }
        public virtual MST_Sites MST_Sites { get; set; }
        public virtual SYS_Roles SYS_Roles { get; set; }
    }
}
